"""change embedding dimensions to 768

Revision ID: 0082ce3e3624
Revises: 1f6313516066
Create Date: 2026-08-06 15:15:43.827845

"""
from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0082ce3e3624'
down_revision: Union[str, Sequence[str], None] = '1f6313516066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks",
        "embedding",
        existing_type=Vector(1536),
        type_=Vector(768),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks",
        "embedding",
        existing_type=Vector(768),
        type_=Vector(1536),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
