"""add search_vector to chunks

Revision ID: 998f10248b03
Revises: 0082ce3e3624
Create Date: 2026-08-18 15:02:10.804019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '998f10248b03'
down_revision: Union[str, Sequence[str], None] = '0082ce3e3624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_chunks_search_vector ON chunks USING GIN (search_vector)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'search_vector')
    op.execute("DROP INDEX IF EXISTS ix_chunks_search_vector")
    # ### end Alembic commands ###
